### ISSUE TITLE
[fix]: title in readme 

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/power-the-web#213]
**Describe the bug**
In Readme.md file, Thank you title not showing correctly. 
![image](https://user-images.githubusercontent.com/88339569/223174867-5d634056-3431-4de4-982d-d64943cf7072.png)

**To Reproduce**
use space after the title and contributors list

**Expected behavior**

**Comment by ujwalkumar1995** [comment]
Hey @devvsakib 
I would like to work on this issue.

**Comment by devvsakib** [comment]
assigned @ujwalkumar1995

**Comment by devvsakib** [comment]
still same. nothing changed. you may forget to add space in the top of the title. 

ex:-

--->

title

**Comment by ujwalkumar1995** [comment]
Hey @devvsakib 
If you look at the below screenshots, space has been added. I have added two <br> tags so that should have added the space.
I can add 1 more br tag but it felt a bit too much space. Please let me know if you still want me to add another br tag.
![Screenshot 2023-03-06 224500](https://user-images.githubusercontent.com/20976813/223183240-8a815caa-700d-4979-999d-7b7f274c6b0d.png)
![Screenshot 2023-03-06 224442](https://user-images.githubusercontent.com/20976813/223183267-4c66e2dd-b2c2-482d-8021-3bece9f7fbd9.png)

**Comment by devvsakib** [comment]
@ujwalkumar1995  this is, how its work in MD file
![image](https://user-images.githubusercontent.com/88339569/223184451-fcf6e1cf-ef68-4b43-abf5-2850c5a4f52f.png)
